### ISSUE TITLE
Use react-create-class instead maybe

### ISSUE THREAD

**Issue by bcomnes** [choojs/nanocomponent-adapters#13]
https://facebook.github.io/react/docs/react-without-es6.html

**Comment by yoshuawuyts** [comment]
I thought this was getting deprecated?

**Comment by bcomnes** [comment]
I thought it was the other way around ha.  I'll have to dig into it some more.

**Comment by toddself** [comment]
it got moved into a separate package (and is deprecated in the main react package).

you should use https://www.npmjs.com/package/create-react-class
